#!/usr/bin/env python3
"""Target-free rho=17 lattice certificate for the frozen K7 JK K3 package.

The construction starts from U + A1(-1)^15.  The 15 negative roots are
labelled by characters of G=(Z/2)^3 in the rho=17 character decomposition.
A doubly-even self-orthogonal binary [15,5] code defines an even overlattice
of index 2^5.  The resulting Neron-Severi lattice has signature (1,16),
|disc|=2^5 and 2-elementary parity delta=1.

Crucially, the code intersections with the four anti-symplectic fixed-coordinate
subspaces are:
  dim(C cap F_tau) = 1, generated by a weight-4 word;
  dim(C cap F_tau_sigma) = 0 for the other three cosets.
Hence the fixed lattices are exactly
  U + D4(-1) + A1(-1)^5   for tau, and
  U + A1(-1)^9            for each tau*sigma,
matching Nikulin types (11,7,1) and (11,9,1).

No neutrino mass, ordering or experimental target is used.
"""

from __future__ import annotations

from itertools import product

# Characters are bits (tau, sigma_A, sigma_B).
# The rho=17 NS character multiplicities are:
#   000 x5 total, of which U contributes two dimensions;
#   100 x0;
#   every other non-trivial character x2.
# Therefore the negative A1 frame contains 000 x3 and the six allowed
# non-trivial characters x2.
CHARS = (
    (0, 0, 0), (0, 0, 0), (0, 0, 0),
    (0, 1, 0), (0, 1, 0),
    (0, 0, 1), (0, 0, 1),
    (1, 1, 0), (1, 1, 0),
    (1, 0, 1), (1, 0, 1),
    (0, 1, 1), (0, 1, 1),
    (1, 1, 1), (1, 1, 1),
)

# One explicit doubly-even self-orthogonal [15,5] code.
# Each tuple lists the support of one generator, zero-based.
GENERATOR_SUPPORTS = (
    (3, 6, 11, 12),
    (0, 2, 4, 5, 6, 9, 12, 13),
    (5, 8, 10, 13),
    (0, 1, 2, 3, 5, 6, 8, 14),
    (1, 6, 7, 8, 9, 10, 11, 14),
)

ANTI = (
    (1, 0, 0),
    (1, 1, 0),
    (1, 0, 1),
    (1, 1, 1),
)
SYMPLECTIC_V4 = (
    (0, 1, 0),
    (0, 0, 1),
    (0, 1, 1),
)


def mask_from_support(support: tuple[int, ...]) -> int:
    out = 0
    for i in support:
        out |= 1 << i
    return out


def span(generators: tuple[int, ...]) -> set[int]:
    out = {0}
    for g in generators:
        out |= {x ^ g for x in tuple(out)}
    return out


def dot2(x: int, y: int) -> int:
    return (x & y).bit_count() & 1


def char_sign(character: tuple[int, int, int], element: tuple[int, int, int]) -> int:
    return -1 if sum(a * b for a, b in zip(character, element)) & 1 else 1


def fixed_coordinate_mask(element: tuple[int, int, int]) -> int:
    mask = 0
    for i, c in enumerate(CHARS):
        if char_sign(c, element) == 1:
            mask |= 1 << i
    return mask


def code_intersection(code: set[int], mask: int) -> list[int]:
    return [c for c in code if c & ~mask == 0]


def log2_power_of_two(n: int) -> int:
    assert n > 0 and n & (n - 1) == 0
    return n.bit_length() - 1


def dual_code(code: set[int]) -> list[int]:
    return [
        v for v in range(1 << 15)
        if all(dot2(v, c) == 0 for c in code)
    ]


def main() -> None:
    generators = tuple(mask_from_support(s) for s in GENERATOR_SUPPORTS)
    code = span(generators)

    # [15,5]
    assert len(code) == 32
    assert log2_power_of_two(len(code)) == 5

    # Doubly even and self-orthogonal.  This is exactly the integrality/evenness
    # condition for adjoining half-sums of A1 roots.
    assert all(c.bit_count() % 4 == 0 for c in code)
    assert all(dot2(a, b) == 0 for a in code for b in code)

    # Starting from U + A1^15, |disc|=2^15.  An index-2^5 overlattice has
    # |disc| = 2^15 / (2^5)^2 = 2^5.
    disc_exponent = 15 - 2 * 5
    assert disc_exponent == 5

    # The discriminant group is C^perp/C, hence dimension 15-2*5=5 over F2.
    cdual = dual_code(code)
    assert len(cdual) == 2 ** 10
    discr_length = log2_power_of_two(len(cdual) // len(code))
    assert discr_length == 5

    # delta=1 witness: an odd-weight vector in C^perp gives half-integral q.
    odd_dual = next(v for v in cdual if v.bit_count() % 2 == 1)
    assert odd_dual.bit_count() % 2 == 1

    # Fixed-locus code intersections.
    anti_report = {}
    for g in ANTI:
        mask = fixed_coordinate_mask(g)
        fixed_coords = mask.bit_count()
        assert fixed_coords == 9
        inter = code_intersection(code, mask)
        dim = log2_power_of_two(len(inter))
        anti_report[g] = (dim, inter)

    tau = ANTI[0]
    assert anti_report[tau][0] == 1
    tau_nonzero = [c for c in anti_report[tau][1] if c]
    assert len(tau_nonzero) == 1
    assert tau_nonzero[0].bit_count() == 4
    for g in ANTI[1:]:
        assert anti_report[g][0] == 0

    # Interpretation:
    # A1^9 plus one weight-4 glue word gives D4 + A1^5 for tau;
    # no glue in the other fixed subspaces leaves A1^9.
    tau_fixed = "U + D4(-1) + A1(-1)^5"
    coset_fixed = "U + A1(-1)^9"

    # Symplectic V4 elements: seven negative fixed coordinates and no code glue.
    # Adding U gives rank 9 in NS.  With rank(T)=5 fixed pointwise, H^2 fixed
    # rank is 14, as required for a Nikulin symplectic involution.
    for g in SYMPLECTIC_V4:
        mask = fixed_coordinate_mask(g)
        assert mask.bit_count() == 7
        assert log2_power_of_two(len(code_intersection(code, mask))) == 0

    # Full-G invariant negative coordinates: the three trivial characters only.
    full_g_fixed_negative = sum(1 for c in CHARS if c == (0, 0, 0))
    assert full_g_fixed_negative == 3
    full_g_invariant_rank = 2 + full_g_fixed_negative  # U plus three negatives
    assert full_g_invariant_rank == 5

    print("rho=17 K7 JK lattice certificate")
    print("================================")
    print("frame                 : U + A1(-1)^15")
    print("code                  : doubly-even self-orthogonal [15,5]")
    print("overlattice index     : 2^5")
    print("NS signature          : (1,16)")
    print("|disc(NS)|            : 2^5")
    print("A_NS length           : 5")
    print("delta                 : 1")
    print("Nikulin lattice type  : (17,5,1)")
    print()
    print("tau fixed lattice     :", tau_fixed)
    print("tau type              : (11,7,1)")
    print("tau*sigma fixed       :", coset_fixed, "(for all three cosets)")
    print("tau*sigma type        : (11,9,1)")
    print()
    print("V4 symplectic NS fixed rank : 9 (for each non-trivial element)")
    print("rank(T_X)                    : 5")
    print("H^2 fixed rank               : 14")
    print("full G invariant rank        :", full_g_invariant_rank)
    print()
    print("code generators (supports):")
    for s in GENERATOR_SUPPORTS:
        print(" ", s)
    print("delta=1 dual witness support:", tuple(i for i in range(15) if odd_dual >> i & 1))
    print()
    print("SCOPE")
    print("  This is an integral lattice/action certificate, not yet an explicit projective K3 equation.")
    print("  Global Torelli/ample-chamber realization, a G-invariant genus-5 polarization,")
    print("  a primitive nef invariant fiber, global JK resolution and heterotic duality remain separate gates.")


if __name__ == "__main__":
    main()
